name: citygliders
description: A chatbot project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  chat_bubbles:
  firebase_core: ^2.10.0
  cloud_firestore: ^4.9.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/button_image.webp

